version: 2

sources:
  - name: RAW_PRAJITA
    description: "Schema for raw input data"
    database: TAG_DEMO_DB
    schema: RAW_PRACH
    tables:
      - name: RAW_CUSTOMERS
        description: "Raw customer dataset loaded from Snowflake"

models:
  - name: customer_clean
    description: "Cleaned customer data prepared from RAW_CUSTOMERS"
    meta:
      PII: "Sensitive"                     # Existing classification in OMD
      classification: "internal"           # Custom governance field
      tags: ["priority", "marketing"]      # ➕ New tags (will be created under dbtTags)
    columns:
      - name: customer_id
        description: "Unique customer identifier"
        meta:
          tags: ["PII.Sensitive", "Tier.Tier1"]   # ✅ Existing tags from OMD

      - name: first_name
        description: "Customer first name"
        meta:
          tags: ["PII.Sensitive", "priority"]      # ✅ + ➕ Combo (existing + new)

      - name: last_name
        description: "Customer last name"
        meta:
          tags: ["PII.Sensitive", "Certification.Gold"]  # ✅ existing

      - name: city
        description: "City of residence"
        meta:
          tags: ["Geo.City", "customer_focus", "dbt_auto_tag"]  # ✅ + ➕

      - name: signup_date
        description: "Customer signup date"
        meta:
          tags: ["Tier.Tier2"]                          # ✅ existing OMD tag
