version: 2

sources:
  - name: RAW_PRAJITA
    description: "Schema for raw input data"
    database: TAG_DEMO_DB
    schema: RAW_PRACH
    tables:
      - name: RAW_CUSTOMERS
        description: "Raw customer dataset loaded from Snowflake"

models:
  - name: customer_clean
    description: "Cleaned customer data"
    meta:
      PII: "Sensitive"
      classification: "internal"
    columns:
      - name: customer_id
        description: "Unique ID"
      - name: first_name
        description: "Customer first name"
        meta:
          tags: ["PII.Sensitive"]
      - name: last_name
        description: "Customer last name"
        meta:
          tags: ["PII.Sensitive"]
      - name: city
        description: "Customer city"
        meta:
          tags: ["Geo.City"]
      - name: signup_date
        description: "Signup date"
